### ISSUE TITLE
MOS has no call for writes to binary files

### ISSUE THREAD

**Issue by envenomator** [breakintoprogram/agon-mos#10]
mos_fputc calls f_putch from fatfs, which writes textfiles, not binary files, adding 0x0a at end of lines.
Would it be possible to create an extra mos_fwrite call to handle byte writes for binary files?

Or, if the intention was to transparently write bytes, then this solves the issue for me - old code commented out

void	mos_FPUTC(UINT8 fh, char c) {
		unsigned int num;
		if(fh > 0 && fh <= MOS_maxOpenFiles) {
		//f_putc(c, &mosFileObjects[fh - 1].fileObject);
		f_write(&mosFileObjects[fh - 1].fileObject, &c, 1, &num); // single byte write
	}
}

**Comment by breakintoprogram** [comment]
Closing this as I've duplicated this card - should be fixed in MOS 1.03 when released.
