### ISSUE TITLE
Documentation about mos_getkbmap

### ISSUE THREAD

**Issue by DjPoke** [breakintoprogram/agon-mos#105]
Hi,
I've seen in BBC BASIC 1.0.6 source code that for the INKEY with negative values, mos_getkbmap is used.
It can be very usefull, for games development, to document this command.

**Comment by breakintoprogram** [comment]
Yes, where possible we use the same keycodes as the Acorn machines. I'll transfer that info to the official docs soon.

**Comment by breakintoprogram** [comment]
Updated the documents with examples.
