### ISSUE TITLE
Implement the low-level FatFS commands in MOS (Stage 1)

### ISSUE THREAD

**Issue by breakintoprogram** [breakintoprogram/agon-mos#11]
Replicate the following C structures in asm:

- FFOBJID - done
- FIL - done
- DIR - done
- FILINFO - done

Add the following methods:

- mos_GETFIL
- mos_FREAD
- mos_FWRITE
- mos_FLSEEK

Implement the following methods:

- ffs_api_fopen - done
- ffs_api_fclose - done
- ffs_api_fread - done
- ffs_api_fwrite - done
- ffs_api_flseek - done
- ffs_api_feof - done
- ffs_api_stat - done

**Comment by HeathenUK** [comment]
I know you certainly don't need any encouragement for this being a worthwhile enhancement, but having spent the day trying to find the least inefficient way of uploading only a portion of a bitmap to VDP _without_ being able to skip unwanted data with fseek(), we could definitely use it 😆
