### ISSUE TITLE
VDU command crashes hard on VDU 23 & VDU 25 

### ISSUE THREAD

**Issue by ukscone** [breakintoprogram/agon-mos#19]
1 parameter VDU functions such as CLS seem to be fine but errors in the VDU 23 & VDU 25 (think it's the ;'s) cause the Agon to freeze up such that a warm boot doesn't work and needs to be power cycled either by pulling the plug or pressing the reset button. Sometime it seems that correct VDU 23 & VDU 25 also freeze up too but can't confirm that 100% yet

**Comment by breakintoprogram** [comment]
No safeguards on badly formed VDU commands.

**Comment by breakintoprogram** [comment]
All possible interactive VDU statements in VDP now timeout if incomplete data is sent to them.
