### ISSUE TITLE
mos_fopen returns 0 after bbcbasic exits

### ISSUE THREAD

**Issue by envenomator** [breakintoprogram/agon-mos#31]
Hi Dean,

An ADL=1 binary, written in C with the standard init.asm from the 'Hello World' example, that opens a file using the bare minimum assembly code for mos_fopen, mos_fopen only works when no bbcbasic.bin has been running previously.
After *bye from bbcbasic, mos_fopen just returns 0
Before running bbcbasic, manually, or from the autoexec.txt, mos_fopen returns a valid filehandle.

I'm attaching a minimalistic example that just fopens/fcloses 'autoexec.txt', and does it statically to avoid using the C arg parser. But opening other existing files behave similarly.
[fopenbug.zip](https://github.com/breakintoprogram/agon-mos/files/11018015/fopenbug.zip)

I have reverted back to running MOS 1.02/VDP 1.02 and also tried bbcbasic 1.02/1.03/1.04.
Thnx!

**Comment by breakintoprogram** [comment]
Issue: In misc.asm

_exec16 preserves MB as it changes it to run 16-bit applications
_exec24 doesn't bother as it does not change MB

Preserve the register in case 24-bit apps change MB
