### ISSUE TITLE
Feature request: sysvar access to the __2nd_jump_table

### ISSUE THREAD

**Issue by envenomator** [breakintoprogram/agon-mos#32]
Can you insert a static sysvar to the __2nd_jump_table? That way ppl would have access to the vectors to change IRQ handlers
I have coded GPIO serial access for my hexload utility, but that currently needs to use a static address from the MOS 1.02 build. It would be great if programs could just retrieve the 2nd_jump_table and access it cleanly from MOS 1.0x onwards.

Access to _set_vector would be ever better, but it's not much code to copy over if we have just the sysvar. Thnx!

**Comment by breakintoprogram** [comment]
Marking as 'Won't Do' as it duplicates the functionality fixed in this card.

https://github.com/breakintoprogram/agon-mos/issues/33
