### ISSUE TITLE
*BYE command takes a long time to return to the MOS prompt.

### ISSUE THREAD

**Issue by lennart-benschop** [breakintoprogram/agon-mos#38]
When I type the *BYE command in Basic, it takes a long time (sometimes a few seconds, sometimes tens of seconds) before it returns to the MOS prompt. When I type keys while waiting, it seems to make that quicker.

It looks like something is amiss with MOS rather than Basic, as the same thing happens with the BYE command in Forth. They both do RST.L 0.

**Comment by breakintoprogram** [comment]
Marking as 'Won't Do' as it is fixed by this card

https://github.com/breakintoprogram/agon-bbc-basic/issues/33
