### ISSUE TITLE
IT layout Keyboard

### ISSUE THREAD

**Issue by weirdocollector** [breakintoprogram/agon-mos#41]
Hi!

I've finally found a PS/2 compatible keyboard, but its Italian layout is currently not supported by the AegonLight 2.

Would it be possible to add this particular layout besides the US and UK ones with a new parameter value to SET KEYBOARD in the autoexec.txt file ?

Thanks a lot.

**Comment by breakintoprogram** [comment]
Already done in MOS/VDP 1.03
