### ISSUE TITLE
Provide HELP command

### ISSUE THREAD

**Issue by leventp** [breakintoprogram/agon-mos#42]
Please provide a HELP command similar to that of BBC Micro:
HELP module

For example:

*HELP MOS 

should display the version of MOS and all available commands. And

*HELP BASIC
should display the version of the installed BASIC

**Comment by leighbb** [comment]
I have created a *HELP command. It can provide help on individual commands (*HELP DIR) and all (*HELP ALL).
I used the Wiki to come up with the help text, but happy for any feedback... See #60

**Comment by breakintoprogram** [comment]
This was added in 1.04 RC3
