### ISSUE TITLE
LOAD command address format

### ISSUE THREAD

**Issue by stevesims** [breakintoprogram/agon-mos#86]
Coming from a background of using Acorn machines, I expect the MOS `LOAD` command to accept/expect an address in hexadecimal.

The BASIC code I've seen that uses `LOAD` via OSCLI seems to consistently use examples that read:
`OSCLI("LOAD file "+STR$(block%))`

That code will produce a decimal address.  I'd have expected to see `STR$~(block%)` to ensure a hexadecimal address were used.

The [documentation for `LOAD`](https://github.com/breakintoprogram/agon-docs/wiki/MOS#load) does not specify the address format, however it does say "addr will default to &40000" which implies a hex address.

**Comment by breakintoprogram** [comment]
MOS defaults to decimal. To use hex, then prefix the address with the ampersand (&) character. This is by design, and is already mentioned in the linked document - point 6 under the heading 'MOS commands'
