### ISSUE TITLE
MOS API calls to undefined commands will fail unpredictably

### ISSUE THREAD

**Issue by stevesims** [breakintoprogram/agon-mos#90]
The `mos_api` routine is very simplistic - it essentially just does a `CALL SWITCH_A`, which essentially just takes the command number (in `A`) as an index into a jump table following that instruction.

There's no bounds checking there at all.  This means that a call to an undefined command number will result in unpredictable behaviour.  The "address" read to jump is likely to be instructions within the MOS code, and not an address at all.

Ideally `mos_api` should ensure that only understood API commands are processed, and reject those it does not understand.

Even more ideally, `mos_api` should support an extension system, allowing new API commands to be added, but that is an idea for another time. 😁

**Comment by breakintoprogram** [comment]
Yes, that's something I've been planning on fixing for a while. A trivial fix, will update.
