### ISSUE TITLE
[help wanted] VBlank from assembly ?

### ISSUE THREAD

**Issue by DjPoke** [breakintoprogram/agon-mos#98]
Hi,
How to wait vblank from ez80 assembly ?

**Comment by breakintoprogram** [comment]
The easiest way to do it is to wait for the least significant byte of sysvar_time to change. That updates on the vblank.
The more complicated way would be to use your own vblank handler.
If you look at the file interrupts.asm in agon-bbc-basic you will see an example of how to do that in Z80 mode, and for an example on how to do that in ADL mode, look at the same file in agon-bbc-basic-adl.
